id = "shades-of-purple-theme"
name = "Shades of Purple Theme"
version = "0.0.5"
schema_version = 1
description = "Shades of purple theme for Zed"
repository = "https://github.com/irmhonde/shades-of-purple-theme"
authors = ["Isheunopa Ralph Mhonde <irmhonde@gmail.com>"]
themes = ["themes/shades-of-purple-theme.json"]
languages = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
